# Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[7643, 7298, 8227, 8165], [7643, 7298, 8227, 5467], [7643, 55, 8227, 8760], [2490, 1821, 1568, 5694, 9272], [2490, 1821, 1568, 5694, 2933], [4062, 7643, 1414, 8227, 9516], [6815, 904, 424, 5694]]


## Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7643 7298 8227 8165]
 [   0    0    0    0 7643 7298 8227 5467]
 [   0    0    0    0 7643   55 8227 8760]
 [   0    0    0 2490 1821 1568 5694 9272]
 [   0    0    0 2490 1821 1568 5694 2933]
 [   0    0    0 4062 7643 1414 8227 9516]
 [   0    0    0    0 6815  904  424 5694]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[-1.62018165e-02  2.93858983e-02  1.93469040e-02  2.77583338e-02
   -2.83431895e-02 -6.99020550e-03  2.89753824e-03  3.26004066e-02
    1.53895877e-02  4.48915623e-02]
  [-1.62018165e-02  2.93858983e-02  1.93469040e-02  2.77583338e-02
   -2.83431895e-02 -6.99020550e-03  2.89753824e-03  3.26004066e-02
    1.53895877e-02  4.48915623e-02]
  [-1.62018165e-02  2.93858983e-02  1.93469040e-02  2.77583338e-02
   -2.83431895e-02 -6.99020550e-03  2.89753824e-03  3.26004066e-02
    1.53895877e-02  4.48915623e-02]
  [-1.62018165e-02  2.93858983e-02  1.93469040e-02  2.77583338e-02
   -2.83431895e-02 -6.99020550e-03  2.89753824e-03  3.26004066e-02
    1.53895877e-02  4.48915623e-02]
  [ 2.57429592e-02  4.37642261e-03  2.37529017e-02  4.54476736e-02
   -3.12801450e-03 -2.39522699e-02 -4.86356877e-02 -6.64088875e-03
    1.39043815e-02 -2.83827670e-02]
  [ 1.19028315e-02 -6.54845312e-03 -3.01229488e-02 -2.97344085e-02
    3.66508625e-02  2.13845037e-02  2.67265700e-02 -4.54160087e-02
   -3.13394219e-

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7643, 7298, 8227, 8165])

In [16]:
print(model.predict(embedded_docs)[0])

[[-0.01620182  0.0293859   0.0193469   0.02775833 -0.02834319 -0.00699021
   0.00289754  0.03260041  0.01538959  0.04489156]
 [-0.01620182  0.0293859   0.0193469   0.02775833 -0.02834319 -0.00699021
   0.00289754  0.03260041  0.01538959  0.04489156]
 [-0.01620182  0.0293859   0.0193469   0.02775833 -0.02834319 -0.00699021
   0.00289754  0.03260041  0.01538959  0.04489156]
 [-0.01620182  0.0293859   0.0193469   0.02775833 -0.02834319 -0.00699021
   0.00289754  0.03260041  0.01538959  0.04489156]
 [ 0.02574296  0.00437642  0.0237529   0.04544767 -0.00312801 -0.02395227
  -0.04863569 -0.00664089  0.01390438 -0.02838277]
 [ 0.01190283 -0.00654845 -0.03012295 -0.02973441  0.03665086  0.0213845
   0.02672657 -0.04541601 -0.03133942 -0.01434959]
 [ 0.01504451  0.02193019  0.01105739 -0.03281379 -0.00966312 -0.03146199
  -0.02086771 -0.03868691  0.04128433 -0.01672295]
 [ 0.03820633  0.00219763 -0.00927185 -0.013556    0.04974971  0.01212182
   0.01913757  0.02993058 -0.0339875  -0.02919276]]
